Info Page
index.php?persons=2&objects=5&lengths=4&max=4&passesmin=3&passesmax=3&jugglerdoes=(4+or+4p)+and+(3+or+3p)+and+2p+and+(1+or+1p)

<p>
	if you click on one of the generated pattens you'll get to the <a href="../info.php?pattern=[p(4,0,4),p(3,1,5),p(1,1,3),p(2,1,4)]&persons=2&back=persons%3D2%26objects%3D5%26lengths%3D4%26max%3D4%26passesmin%3D3%26passesmax%3D3%26jugglerdoes%3D%25284%2Bor%2B4p%2529%2Band%2B%25283%2Bor%2B3p%2529%2Band%2B2p%2Band%2B%25281%2Bor%2B1p%2529%26exclude%3D%26clubdoes%3D%26react%3D%26results%3D42" target="PrechacThis">info page</a> of that pattern.
</p>

<p>
	Here you can transform a throw by clicking on the up and down arrows. The right and left arrows rotate the pattern.
	...
</p>
