Basics
index.php?persons=2&objects=4+or+5&lengths=3+or+4&max=3&passesmin=1&passesmax=3

<ul>
	<li><strong>Jugglers:</strong><br>number of jugglers is 2</li>
	<li><strong>Objects:</strong><br>number of clubs is 4 or 5</li> 
	<li><strong>Period:</strong><br>length of the pattern is 3 or 4</li>
	<li><strong>Max height:</strong><br>maximum height of throws is 3</li>
	<li><strong>Passes:</strong><br>at least 1 and at most 3 passes</li>
</ul>
<p>If you need more information on symmetric passing patterns in genreal, have a look <a href="http://en.wikibooks.org/wiki/Symmetric_Passing_Patterns" target="_blank">here</a>.</p>