Contain
index.php?persons=2&objects=4&lengths=4&max=4&jugglerdoes=2p+and+1+1p

<p>A <a href="../index.php?persons=2&objects=4&lengths=4&max=4&passesmin=1&jugglerdoes=4+and+1+1p" target="PrechacThis">first example</a> 
searches for all patterns containing a 4 <strong>and</strong> the sequence "1 1p".</p>

<p>The <a href="../index.php?persons=2&objects=4&lengths=4&max=4&passesmin=1&jugglerdoes=4+or+1+1p" target="PrechacThis">second example</a> 
	searches for all patterns containing a 4 <strong>or</strong> the sequence "1 1p".</p>
